-- Part1: generate augmented matrix A for general polynomial with n variables and d degree f with coefficients c_\alpha

-- generate the ring "Rl" of {x_1...x_n, c_{\alpha}, g_11...g_nn, w_\beta}, where \sum\alpha_i = d and g_ij is entry of matrix in lie algebra. 
-- w_\beta is defined as follows.  
-- Assume that f = \prod_{i=1}^k f_i^{p_i} and every f_i has degree d_i. w_\beta are the coefficients for f_i.
-- For example, f = (w_{120}x_1^2+w_{111}x_1x_2+w_{102}x_2^2)(w_{210}x_1+w_{201}x_2), the first index of beta corresponds to the i-th factor f_i, 
-- the other indices of beta correponds to n interger sum to d_i. 
-- Input: number of variables "n" and listfactor = {d_1, ...d_k} and listpower = {p_1, ...., p_k}
-- Output: ring "Rl"
generateRing = method()
generateRing(ZZ, List, List) := (n, listfactor, listpower) ->  (     
    -- parameters w_\beta "coelist"
    coelist = for k from 1 to length(listfactor) list(
        apply(compositions(n, listfactor_(k-1)), i -> (value("w" | toString(k) | concatenate(apply(i, j -> toString j)))))
    );
    coelist = flatten coelist;
    -- total degree d = \sum_{i=1}^k (listfactor_i)*(listpower_i)
    d = sum(apply((toList(0..length(listfactor)-1)), i -> (listfactor_i)*(listpower_i)));
    -- parameters c_\alpha
    params = apply(compositions(n, d), i -> (value("c" | concatenate(apply(i, j -> toString j)))));
    -- g_ij
    g = apply(toList(1..n) ** toList(1..n), i -> "g" | toString i#0 | toString i#1);
    -- ring of {x_1...x_n, c_{\alpha}, g_11...g_nn, w_\beta}
    Rl := QQ[x_1..x_n, params, g, coelist];
    return Rl
    )

-- generate the generic polynomial "f" with n variables and d degree
-- Input: number of variables "n", degree "d" and the ring "Rl"
-- Output: polynomial "f"
generateFunction = method()
generateFunction(ZZ, ZZ, Ring) := (n, d, Rl) -> (
    -- generate the generic polynomial f -- "f"
    f := sum(toList(0..(length(compositions(n, d))-1)) / (i -> Rl_(i+n) * (product(toList(0..(n-1)) / (j -> Rl_j^(((compositions(n, d))#i)#j))))));
    return f 
    )

-- generate the matrix A such that A*g = \vec{g *action f} with entries in c_\alpha
-- Input: number of variables "n", degree "d" and ring "Rl"
-- Output: matrix "A"
generateMatrix = method()
generateMatrix(ZZ, ZZ, Ring) := (n, d, Rl) -> (
    -- generate polynomial g*f -- "gstarf"
    fterms = toList(0..(length(compositions(n, d))-1)) / (i -> Rl_(i+n) * product(toList(0..(n-1)) / (j -> Rl_j^(((compositions(n, d))#i)#j))));
    ftermsexp = compositions(n, d);
    gstarf = sub(sum(0..(length(fterms)-1), j -> (sum(1..n, i -> (innerSum = sum(1..n, k -> Rl_((i-1)*n+k-1+n+length(compositions(n, d))) * Rl_(k-1)); sub(ftermsexp#j#(i-1), Rl) * (sub(1,Rl)/Rl_(i-1)) * fterms#j * innerSum)))), Rl);
    -- get the coefficients for monomials x_\alpha in g*f -- "vecgstarf"
    (monomialsx, vecgstarf) = coefficients(gstarf,  Variables => toList(0..(n-1)) / (i -> Rl_i));
    -- get matrix A -- "MatrixA"
    (gij, MatrixA) = coefficients(matrix{flatten entries vecgstarf},  Variables => toList((n+length(compositions(n, d)))..(n+length(compositions(n, d))-1+n^2)) / (i -> Rl_i));
    MatrixA
    )

-- Part2: analyse the matrix substituting the coefficients for f_i

-- generate relation between c_\alpha and w_\beta
-- Input: number of variables "n", ring "Rl", list of degree of every factor f_i and list of power of every factor f_i in f
-- Output: relation
generateRelation = method()
generateRelation(ZZ, Ring, List, List) := (n, Rl, listfactor, listpower) -> (
    -- write f with parameters w_\beta "fw"
    fw = 1;
    for k from 0 to length(listpower)-1 do (
        term = 0;
        for j  from 0 to length(compositions(n, listfactor_k))-1 do (
            coe = Rl_(n+length(compositions(n, d))+n^2+sum(apply(toList(0..k), i -> length(compositions(n, listfactor_i))))-length(compositions(n, listfactor_k))+j);
            mon = product(apply(toList(0..n-1), i -> Rl_i^(((compositions(n, listfactor_k))_j)_i)));
            term = term + coe*mon;
        );
        fw = fw * term^(listpower_k);
    );
    -- get the relations generated by c_\alpha => coefficient of x_\alpha in fw -- "genelist"
    (monoline,coeffline) = coefficients(fw,  Variables => toList(0..(n-1)) / (i -> Rl_i));   
    coefflinelist = flatten entries coeffline;
    genelist = toList(0..(length(compositions(n, d))-1)) / (i -> (Rl_(i+n) => coefflinelist#i));
    return genelist
)

-- Example for n=3, d=3, listfactor = {2, 1} and listpower = {1, 1}
n = 3;
listfactor = {1, 1};
listpower = {2, 1};
d = sum(apply((toList(0..length(listfactor)-1)), (i -> (listfactor_i)*(listpower_i))));
-- ring 
Rl = generateRing(n, listfactor, listpower) 
-- polynomial
f = generateFunction(n, d, Rl)
-- matrix
A = generateMatrix(n, d, Rl)
-- relation between c_\alpha and w_\beta
genelist = generateRelation(n, Rl, listfactor, listpower)
-- ring of w_\beta "Rc"
coelist = for k from 1 to length(listfactor) list(
        apply(compositions(n, listfactor_(k-1)), i -> (value("w" | toString(k) | concatenate(apply(i, j -> toString j)))))
    );
coelist = flatten coelist;
Rc := QQ[coelist]
-- matrix with entries in QQ[w_\beta] by substituting the relation
Anew = sub(sub(A, genelist), Rc)
-- ideal generated by all 4 minors of Anew and transfer to ring Rc
I1 = sub(minors(4, Anew), Rc)