-- generate the ring "Rl" of {x_1...x_n, c_{\alpha_1 ... \alpha_n}, a_11,...,a_nn, g_11...g_nn}, where \sum\alpha_i = n
--          and -a_ij corresponds to the constant in ij-entry in Hess(f)
-- Input: number of variables "n" and degree of monomials "n"
-- Output: ring "Rl"
generateRing = method()
generateRing(ZZ) := (n) ->  (
    -- c_\alpha
    params1 = apply(compositions(n, n), i -> (value("c" | concatenate(apply(i, j -> toString j)))));
    -- a_ij
    params2 =  apply(toList(1..(n-1)) ** toList(1..(n-1)), i -> "a" | toString i#0 | toString i#1);
    -- g_ij
    g = apply(toList(1..n) ** toList(1..n), i -> "g" | toString i#0 | toString i#1);
    -- generate the ring 
    Rl := QQ[x_1..x_n, params1, g, params2];
    return Rl
    )

-- generate the homogenized determinant of Hess(f) with n-1 original variables x_1...x_{n-1} and x_n is the variable introduced for homogenization
-- Input: number of variables "n" and ring "Rl"
-- Output: polynomial 
generateFunction = method()
generateFunction(ZZ, Ring) := (n, Rl) -> (
    -- x_0 = 1 - x_1...-x_{n-1} -- "S"
    S = 1 - sum(1..(n-1), i -> Rl_(i-1));
    lengthc = length(compositions(n, n));
    -- Hess(f) -- "H"
    matrixEntries = for i from 1 to n-1 list (
        for j from 1 to n-1 list (
            if i == j then (
                1/S + 1/(Rl_(i-1)) - Rl_(n+lengthc+n^2+(i-1)*(n-1) + (j-1))
            ) else (
                1/S - Rl_(n+lengthc+n^2+(i-1)*(n-1) + (j-1))
            )
        )
    );
    H = matrix(frac(Rl), matrixEntries);
    -- determinant of H multiply by the common denominator -- "polydetH"
    polydetH = sub(det(H)*S*product(1..(n-1), i -> Rl_(i-1)), Rl);
    -- homogenize polydetH -- "homopolydetH"
    numVars := numgens Rl;
    weights := for i from 0 to numVars-1 list (
        if i < n then 1 else 0  
    );
    hompolydetH = homogenize(polydetH, Rl_(n-1), weights);
    return hompolydetH
    )

-- generate the relations between aij and c_\alpha
-- Input: number of variables "n", ring "Rl" and polynomial "homopolydetH"
-- Output: a list of relations {c_\alpha => polynomial of a_ij}
generateRelation = method()
generateRelation(ZZ, Ring, RingElement) := (n, Rl, homopolydetH) -> (
    -- get monomials and corresponding coefficients in homopolydetH
    (var,coe) = coefficients(homopolydetH, Variables => toList(0..(n-1)) / (i -> Rl_i));
    coelist = flatten(entries coe);
    varlist = flatten(entries var);
    explist = toList(1..length(varlist)) / (i -> ((exponents sub(varlist_(i-1), QQ[x_1..x_n]))_0));
    genelist = {};
    -- if x^\alpha appear in homopolydetH, then append the relation c_\alpha => coefficient of x^\alpha in homopolydetH
    -- if x^\alpha does not appear in homopolydetH, then append the relation c_\alpha => 0
    for i from 0 to length(compositions(n, n))-1 do (
        po = position(explist, j -> j == (compositions(n, n))_i);
        if po === null then (
            genelist = append(genelist, Rl_(n+i) => 0)
        ) else (
            genelist = append(genelist, Rl_(n+i) => coelist_po)
        )
    );
    return genelist 
)

-- generate the matrix A such that A*g = \vec{g *action f} with entries in c_\alpha
-- Input: number of variables "n", degree of monomials "n" and ring "Rl" = generateRing(n)
-- Output: matrix "A"
generateMatrix = method()
generateMatrix(ZZ, ZZ, Ring) := (n, d, Rl) -> (
    -- generate polynomial g*f -- "gstarf"
    fterms = toList(0..(length(compositions(n, d))-1)) / (i -> Rl_(i+n) * product(toList(0..(n-1)) / (j -> Rl_j^(((compositions(n, d))#i)#j))));
    ftermsexp = compositions(n, d);
    gstarf = sub(sum(0..(length(fterms)-1), j -> (sum(1..n, i -> (innerSum = sum(1..n, k -> Rl_((i-1)*n+k-1+n+length(compositions(n, d))) * Rl_(k-1)); sub(ftermsexp#j#(i-1), Rl) * (sub(1,Rl)/Rl_(i-1)) * fterms#j * innerSum)))), Rl);
    -- get the coefficients for monomials x_\alpha in g*f -- "vecgstarf"
    (monomialsx, vecgstarf) = coefficients(gstarf,  Variables => toList(0..(n-1)) / (i -> Rl_i));
    -- get matrix A -- "MatrixA"
    (gij, MatrixA) = coefficients(matrix{flatten entries vecgstarf},  Variables => toList((n+length(compositions(n, d)))..(n+length(compositions(n, d))-1+n^2)) / (i -> Rl_i));
    return MatrixA
    )

-- Example for n=3
-- ring 
Rl = generateRing(3)
-- polynomial
homopolydetH = generateFunction(3, Rl)
-- matrix
A = generateMatrix(3, 3, Rl)
-- relation between c_\alpha and aij
genelist = generateRelation(3, Rl, homopolydetH)
-- matrix with entries in QQ[aij] by substituting the relation
Anew = sub(A, genelist)
-- ring of aij
Rc := QQ[apply(toList(1..(n-1)) ** toList(1..(n-1)), i -> "a" | toString i#0 | toString i#1)]
-- ideal generated by all r minors of Anew and transfer to ring Rc
I1 = sub(minors(4, Anew), Rc)